# SPDX-FileCopyrightText: 2023 Comcast Cable Communications Management, LLC
# SPDX-License-Identifier: Apache-2.0

---
linters:
  enable:
    - errorlint
    - funlen
    - goconst
    - gosec
    - misspell
    - unconvert
    - prealloc
  disable:
    - errcheck
    - ineffassign
    - dupl
    - bodyclose

issues:
  exclude-rules:
    - path: _test.go
      linters:
        - funlen
        - gosec

linters-settings:
  errorlint:
    # Report non-wrapping error creation using fmt.Errorf
    errorf: false
  misspell:
    locale: US
